apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alpha-innotec-bigquery-exporter.fullname" . }}
  labels:
    {{- include "alpha-innotec-bigquery-exporter.labels" . | nindent 4 }}
data:
  heatpump-host-ip: {{ .Values.config.heatpumpHostIP | quote }}
  heatpump-host-port: {{ .Values.config.heatpumpHostPort | quote }}
  heatpump-unit-id: {{ .Values.config.heatpumpUnitID | quote }}
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}