apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-alpha-innotec-exporter.fullname" . }}
  labels:
    {{- include "jarvis-alpha-innotec-exporter.labels" . | nindent 4 }}
data:
  websocket-host-ip: {{ .Values.config.websocketHostIP | quote }}
  websocket-host-port: {{ .Values.config.websocketHostPort | quote }}
  websocket-login-code: {{ .Values.config.websocketLoginCode | quote }}
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}
  config.yaml: |
    {{- with .Values.config.configYaml }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}